### ISSUE TITLE
What about code security [CSHTML5]

### ISSUE THREAD

**Issue by pooran** [OpenSilver/OpenSilver.Samples.Showcase#2]
I can see the code logic.. no XAML that is understandable, code behind is compiled to JS. Is there an option to obfuscate the code?

**Comment by cshtml5** [comment]
CSHTML5 uses Bridge.NET internally, which produces both obfuscated and non-obfuscated code. Just go to the bin/Debug/Output folder and you will see "index.min.html" as well as the minified JS files. You can choose to generate only minified code by changing the settings in the "bridge.json" file located in your project root.

**Comment by giovanni-a** [comment]
Closed the issue because the Showcase now uses OpenSilver instead of CSHTML5 so the code is no longer compiled to JavaScript but instead it is compiled to WebAssembly, which provides much better obfuscation.
